
```{r}
library(tidyverse)
library(here)
library(zoo)
library(corrplot)
```

```{r}
liga <- "brasileirao_a"

df <- readRDS(here("data", paste0("database_", liga, ".rds")))
```

```{r}
head(df)
```


```{r}
df_processed <- df |>
  mutate(
    'gols_xg.casa' = gols_casa - gols_esperados.casa,
    'gols_xg.fora' = gols_fora - gols_esperados.fora,
    
    'gols_xg_contra.casa' = gols_casa - gols_esperados.fora,
    'gols_xg_contra.fora' = gols_fora - gols_esperados.casa,
    
    'taxa_chute_a_gol.casa' = if_else(chutes.casa == 0, 0, chutes_a_gol.casa / chutes.casa),
    'taxa_chute_a_gol.fora' = if_else(chutes.fora == 0, 0, chutes_a_gol.fora / chutes.fora),
    
    'gols_por_chute.casa' = if_else(chutes.casa == 0, 0, gols_casa / chutes.casa),
    'gols_por_chute.fora' = if_else(chutes.fora == 0, 0, gols_fora / chutes.fora),
    
    'gols_por_chute_a_gol.casa' = if_else(chutes_a_gol.casa == 0, 0, gols_casa / chutes_a_gol.casa),
    'gols_por_chute_a_gol.fora' = if_else(chutes_a_gol.fora == 0, 0, gols_fora / chutes_a_gol.fora),
    
    # Resultados dos ultimos 3 jogos (ou pontos)
    # Pontos ate aquela partida
    # Gols feitos ou sofridos
  ) |> 
  arrange(data) |> 
  mutate(match_id = row_number())

```

```{r}
window <- 3

home_stats <- df_processed |> 
  select(
    match_id,
    temporada,
    rodada,
    data, 
    hora,
    time_casa, 
    dplyr::contains(".casa")
  ) |> 
  group_by(time_casa, temporada) |> 
  mutate(
    across(
      .cols = where(is.numeric) & !c(match_id, rodada),
      .fns = ~ zoo::rollmean(.x, k = window, fill = NA, align = "right"),
      .names = "{.col}_mm{window}.casa"
    )
  ) |> 
  ungroup() |> 
  select(
    match_id,
    dplyr::contains("_mm")
  )

away_stats <- df_processed |> 
  select(
    match_id,
    temporada,
    rodada,
    data, 
    hora,
    time_fora, 
    dplyr::contains(".fora")
  ) |> 
  group_by(time_fora, temporada) |> 
  mutate(
    across(
      .cols = where(is.numeric) & !c(match_id, rodada),
      .fns = ~ zoo::rollmean(.x, k = window, fill = NA, align = "right"),
      .names = "{.col}_mm{window}.fora"
    )
  ) |> 
  ungroup() |> 
  select(
    match_id,
    dplyr::contains("_mm")
  )



team_stats <- df_processed |> 
  left_join(home_stats, by = "match_id") |> 
  left_join(away_stats, by = "match_id")
```

```{r}
home_stats <- team_stats |> 
  select(
    match_id,
    temporada,
    data,
    rodada,
    time = time_casa,
    contains(".casa")
  ) |> 
  mutate(
    local = "casa"
  ) |> 
  rename_with(~ str_remove(.x, "\\.casa$"), .cols = dplyr::contains(".casa"))

away_stats <- team_stats |> 
  select(
    match_id,
    temporada,
    data,
    rodada,
    time = time_fora,
    contains(".fora")
  ) |> 
  mutate(
    local = "fora"
  ) |> 
  rename_with(~ str_remove(.x, "\\.fora$"), .cols = dplyr::contains(".fora"))


team_stats2 <- bind_rows(home_stats, away_stats) |> 
  arrange(temporada, data, rodada) |> 
  group_by(time, temporada) |> 
  select(-contains("_mm")) |> 
  mutate(
    across(
      .cols = where(is.numeric) & !c(match_id, rodada),
      .fns = ~ zoo::rollmean(.x, k = window, fill = NA, align = "right"),
      .names = "{.col}_mm{window}.time"
    )
  ) |> 
  ungroup() |> 
  select(
    match_id,
    time,
    contains(".time")
  )


df_processed_final <- team_stats |> 
  left_join(team_stats2, by = c("match_id", "time_casa" = "time"), suffix = c("_casa", "_remover")) |> 
  left_join(team_stats2, by = c("match_id", "time_fora" = "time"), suffix = c("_fora", "_remover")) |> 
  select(-contains("_remover"))
  
```

```{r}
data <- df_processed_final |> 
  select(
    match_id,
    temporada,
    rodada,
    data,
    dia,
    hora,
    publico,
    arbitro,
    time_casa,
    gols_casa,
    gols_fora,
    time_fora,
    resultado,
    contains("_mm")
  )

train <- data |> 
  filter(
    temporada != 2025,
    !(temporada == 2024 & rodada %in% 30:38)
  )

test <- data |> 
  filter(
    temporada != 2025,
    (temporada == 2024 & rodada %in% 30:38)
  )


train_test <- list(
  train = train,
  test = test
)
```

```{r}
saveRDS(train_test, paste0("../data/train_test/", liga, ".rds"))
```

